services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: hidrants-back
    restart: unless-stopped
    ports:
      - '127.0.0.1:3034:3033'
    env_file:
      - ./back/.env
    volumes:
      - ./back/data:/app/data
    networks:
      - hidrants-net
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3033/api/adfs']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: hidrants-front
    restart: unless-stopped
    ports:
      - '127.0.0.1:8080:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hidrants-net
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    networks:
      - hidrants-net

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  hidrants-net:
    driver: bridge
